# Use a Node.js base image
FROM node:16-alpine as build-stage

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./package*.json /app/

# Install project dependencies
RUN npm install

# Copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . /app/

# Build the app for production
RUN npm run build

# Use Nginx to serve the static files
FROM nginx:stable-alpine as production-stage

# Copy your custom server block configuration
COPY ./wasessen_server.conf /etc/nginx/sites-enabled/default

# Copy the built app to Nginx's serve directory
COPY --from=build-stage /app/.svelte-kit /usr/share/nginx/html

# Expose port 80 to the outside
EXPOSE 80

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]